# @package __global__

defaults:
  - musicgen/default
  - /model: lm/musicgen_lm
  - override /dset: audio/musiccaps_audio
  - _self_

autocast: true
autocast_dtype: float16

compression_model_checkpoint: //pretrained/facebook/encodec_32khz

channels: 1
sample_rate: 32000

deadlock:
  use: true  # deadlock detection

continue_from: //pretrained/facebook/musicgen-small

dataset:
  batch_size: 8  # Smaller batch for fine-tuning
  sample_on_weight: false  # Uniform sampling all the way
  sample_on_duration: false  # Uniform sampling all the way

generate:
  lm:
    use_sampling: true
    top_k: 250
    top_p: 0.0

optim:
  epochs: 10  # Fine-tuning epochs
  optimizer: dadam
  lr: 1e-5  # Lower LR for fine-tuning
  ema:
    use: true
    updates: 10
    device: cuda

logging:
  log_tensorboard: true